#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#  jpa:
#    hibernate:
#      ddl-auto: update

spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        page-parameter: current
        size-parameter: size
        max-page-size: 15

  servlet:
    multipart:
      max-file-size: 10MB

#  profiles:
#    active:
#      -dev


#  jackson:
#    mapper:
#      DEFAULT_VIEW_INCLUSION: true


hoaxify:
  upload-path: files
#  ---
#  spring:
#    profiles: prod
#  hoaxify:
#    upload-path: storage-prod
#  ---
#  spring:
#    profiles: dev
#  hoaxify:
#    upload-path:storage-dev